# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26e997a34cdee9dfc13817e371996b1f1716b85d5f2907fb71b463b1d15abe49dc52405745957bff94dd72997958a9a57aa8cba3c9aed2133862b54f80486b0a

test:
  secret_key_base: 3713fa2ebc79f7d763fe4c842fe690cb24c41c4191adfd687b1a6bf35c4997d7a74c0cdecb0193a77d8958f5bad385e1e9e29f36df0c2a222c207ac71e8ae2c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
